---
title: "linear_corn(corn)"
author: "Yenan Guan"
date: "3/31/2018"
output: html_document
---

## Import File
```{r}
rm(list = ls())
library(readr)
corn.data <- read_csv("~/Downloads/Flatfile_Corn_3.30.csv")
corn.data = data.frame(corn.data)
names(corn.data)
```

delete the redundant variables
```{r}
corn.data = corn.data[, !names(corn.data) %in% c("X1", "GRWR_ADDR_CITY_NM", "GRWR_ADDR_POSTL_CD")]
```

delete the KPIs in categorical forms and delete RADL&RFM
```{r}
corn.data = corn.data[, !names(corn.data) %in% c("RADL_SCR_FY", "RADL_SCR_FYM1", "PURCH_PRBLTY_DESC_FY", "PURCH_PRBLTY_DESC_FYM1", "RFM_SCR_FY", "RFM_RANGE_FY", "RFM_SCR_FYM1", "RFM_RANGE_FYM1")]

corn.data = corn.data[, !names(corn.data) %in% c("MON_AREA_FYM2", "MON_AREA_FYM3", "MON_AREA_FYM4", "MON_AREA_FYM5", "MON_AREA_FYM6", "MON_AREA_TOTAL", "OPPO_CROP_AREA_TOTAL", "MON_AREA_FYM1_sum", "MON_AREA_FYM2_sum", "MON_AREA_FYM3_sum", "MON_AREA_FYM4_sum", "MON_AREA_FYM5_sum", "MON_AREA_FYM6_sum", "TOTAL_AREA_FYM1")]
```

delete GNSQ_sum
```{r}
corn.data = corn.data[, !names(corn.data) %in% c("GNSQ_TOTAL", "GNSQ_FYM1_sum", "GNSQ_FYM2_sum", "GNSQ_FYM3_sum", "GNSQ_FYM4_sum","GNSQ_FYM5_sum", "GNSQ_FYM6_sum")]
```

delete sales amount in dollar value
```{r}
corn.data = corn.data[, !grepl("NET_SLS_AMT_FY.*", names(corn.data))]
```

## Region
```{r}
corn.data$"IL" = 0
corn.data$"IA" = 0
corn.data$"MI/KY/IN" = 0
corn.data$"MN/WI" = 0
corn.data$"MO/KS/CO" = 0
corn.data$"ND/SD" = 0
corn.data$"NE" = 0
corn.data$"OH/NorthEastern" = 0
corn.data$"Unknown" = 0

corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "IL", "IL"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "IA", "IA"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "MI", "MI/KY/IN"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "KY", "MI/KY/IN"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "IN", "MI/KY/IN"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "MN", "MN/WI"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "WI", "MN/WI"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "MO", "MO/KS/CO"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "KS", "MO/KS/CO"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "CO", "MO/KS/CO"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "ND", "ND/SD"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "SD", "ND/SD"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "NE", "NE"] = 1
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "OH", "OH/NorthEastern"] = 1
NEstates = c("CT", "DE", "ME", "MD", "MA", "NH", "NJ", "NY", "PA", "RI", "VT")
corn.data[corn.data$GRWR_ADDR_ST_PRVNC %in% NEstates, "OH/NorthEastern"] = 1 #checked from Wikipedia
corn.data[corn.data$GRWR_ADDR_ST_PRVNC == "Unknown", "Unknown"] = 1

corn.data = corn.data[, !grepl("GRWR_ADDR_ST_PRVNC", names(corn.data))]
```

## Generate other new variables - sum of FYM2-FYM6 for the certain brand and other brands
```{r}
# calculate sum of GNSQ_FYM2-FYM6
colnames(corn.data)[names(corn.data) == "GNSQ_FYM1_other"] = "GNSQ_FY16_other"
corn.data$GNSQ_sumLag_other = rowSums(corn.data[,grepl("GNSQ_FYM.*other",names(corn.data))])
corn.data = corn.data[, !grepl("GNSQ_FYM.*_other",names(corn.data))]

colnames(corn.data)[names(corn.data) == "GNSQ_FYM1"] = "GNSQ_FY16"
corn.data$GNSQ_sumLag = rowSums(corn.data[,grepl("GNSQ_FYM.*",names(corn.data))])
corn.data = corn.data[, !grepl("GNSQ_FYM.*",names(corn.data))]
colnames(corn.data)[names(corn.data) == "GNSQ_FY16"] = "GNSQ_FYM1"
colnames(corn.data)[names(corn.data) == "GNSQ_FY16_other"] = "GNSQ_FYM1_other"
```

## change the column order
```{r}
# corn.data = cbind(corn.data[c("GRWR_ID", "CROP_NM", "BRND_DESC")], corn.data[ , -which(names(corn.data) %in% c("GRWR_ID", "CROP_NM", "BRND_DESC"))])

corn.data = corn.data[, cbind("GRWR_ID", "CROP_NM", "BRND_DESC", "GNSQ_FY", "GNSQ_FYM1", "GNSQ_sumLag", "GNSQ_FYM1_other", "GNSQ_sumLag_other", "MON_AREA_FY", "MON_AREA_FYM1", "OPPO_CROP_AREA_FY", "OPPO_CROP_AREA_FYM1", "RECENCY_SCORE_FY", "RECENCY_SCORE_FYM1", "FREQUENCY_SCORE_FY", "FREQUENCY_SCORE_FYM1", "MONETARY_SCORE_FY", "MONETARY_SCORE_FYM1", "PURCH_PRBLTY_FY", "PURCH_PRBLTY_FYM1", "IL", "IA", "MI/KY/IN", "MN/WI", "MO/KS/CO", "ND/SD", "NE", "OH/NorthEastern", "Unknown" )]
names(corn.data)
```

## Categorize variables
```{r}
corn_region = corn.data[,c("IL","IA","MI/KY/IN","MN/WI","MO/KS/CO","ND/SD","NE","OH/NorthEastern","Unknown")]
corn_RFM_FYM1 = corn.data[, c("RECENCY_SCORE_FYM1", "FREQUENCY_SCORE_FYM1", "MONETARY_SCORE_FYM1")]
corn_AREA_FYM1 = corn.data[, c("MON_AREA_FYM1", "OPPO_CROP_AREA_FYM1")]
corn_KPI_FYM1 = corn.data[, c("RECENCY_SCORE_FYM1", "FREQUENCY_SCORE_FYM1", "MONETARY_SCORE_FYM1", "PURCH_PRBLTY_FYM1")]
```

# Regression: linear + logit
prep
```{r}
n = dim(corn.data)[1]
set.seed(1)
train = sample(n, 0.9*n)
```

### dat1
```{r}
attach(corn.data)
var = c("GRWR_ID", "GNSQ_FY", "BRND_DESC")
dat1 = cbind(corn.data[,var], 
             GNSQ_FYM1,
             GNSQ_sumLag,
             GNSQ_FYM1_other,
             GNSQ_sumLag_other,
             corn_region,
             corn_AREA_FYM1,
             corn_KPI_FYM1)

lm.fit=lm(GNSQ_FY~., data = dat1[train,-which(names(dat1) == "GRWR_ID")])
lm.pred = predict(lm.fit, newdata = dat1[-train,-which(names(dat1) == "GRWR_ID")])

var = c("GRWR_ID", "GNSQ_FY")
dat1$purchase = 1
dat1[dat1$GNSQ_FY == 0, "purchase"] = 0
glm.fit = glm(purchase ~., data = dat1[train, -which(names(dat1) == var)], family = binomial)
glm.pred = predict(glm.fit, dat1[-train, -which(names(dat1) == var)], type = "response")
dat1$glmpred = 0
dat1[-train, "glmpred"] = glm.pred
dat1$pur.pred = 0
dat1[dat1$glmpred > 0.5, "pur.pred"] = 1
mean(dat1[-train, "pur.pred"] == dat1[-train, "purchase"])
```






